#!name=local/patches-unlock.sgmodule-gaps

[Rule]
# >>> local/patches-unlock.sgmodule gaps
DOMAIN,msmp.abchina.com.cn,REJECT
DOMAIN-SUFFIX,ocsp-lb.apple.com.akadns.net,REJECT
DOMAIN-SUFFIX,ocsp.apple.com,REJECT
DOMAIN-SUFFIX,ocsp.g.aaplimg.com,REJECT
DOMAIN,ns.itunes.apple.com,REJECT
DOMAIN,updates.cdn-apple.com,REJECT
DOMAIN,updates-http.cdn-apple.com,REJECT
DOMAIN-SUFFIX,appldnld.apple.com,REJECT
DOMAIN-SUFFIX,mesu-cdn.apple.com.akadns.net,REJECT
DOMAIN,swscan.apple.com,REJECT
DOMAIN,swdist.apple.com,REJECT
DOMAIN,swdownload.apple.com,REJECT

[MITM]
# >>> local/patches-unlock.sgmodule gaps
hostname = %APPEND% skip-server-cert-verify = true
