#!name=local/spotify-unlock.sgmodule-gaps

[URL Rewrite]
# >>> local/spotify-unlock.sgmodule gaps
^https:\/\/(spclient\.wg\.spotify\.com|.*-spclient\.spotify\.com(:443)?)\/user-customization-service\/v1\/customize$ header-del if-none-match

[MITM]
# >>> local/spotify-unlock.sgmodule gaps
hostname = %APPEND% *spclient.spotify.com

[Script]
# >>> local/spotify-unlock.sgmodule gaps
spotifyProto-nocache = type=http-request, pattern=^https:\/\/(spclient\.wg\.spotify\.com|.*-spclient\.spotify\.com(:443)?)\/user-customization-service\/v1\/customize$, script-path=https://raw.githubusercontent.com/oo226/egern-config/refs/heads/cursor/adblock-formal-f611/Unlock/js/raw.githubusercontent.com/oo226/egern-config/refs/heads/main/Scripts/spotify-del-cache-headers.js, timeout=10
spotifyProto = type=http-response, pattern=^https:\/\/(spclient\.wg\.spotify\.com|.*-spclient\.spotify\.com(:443)?)\/(bootstrap\/v1\/bootstrap|user-customization-service\/v1\/customize)$, requires-body=true, binary-body-mode=true, max-size=0, timeout=10, script-path=https://raw.githubusercontent.com/oo226/egern-config/refs/heads/cursor/adblock-formal-f611/Unlock/js/raw.githubusercontent.com/oo226/egern-config/refs/heads/main/Scripts/_external/github-raw/Amlabort/MY_clash/main/files/lpx/js/spot-proto-eevee.js
