#!/usr/bin/env python3
"""Convert mirrored app .list files into Egern yaml rule-sets."""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from paths import ROUTING_FOREIGN, ROUTING_UPSTREAM
from routing_list_utils import count_sets, parse_surge_list, write_egern_sets

APP_DIR = ROUTING_UPSTREAM / "app-lists"
OUTPUT_DIR = ROUTING_FOREIGN / "App"

APP_LABELS = {
    "WeChat": "blackmatrix7 — 微信",
    "Weibo": "blackmatrix7 — 微博",
    "Bilibili": "blackmatrix7 — 哔哩哔哩",
    "TikTok": "blackmatrix7 — TikTok 海外",
    "Douyin": "fmz200 — 抖音大陆",
    "RedBook": "fmz200 — 小红书",
    "KuaiShou": "fmz200 — 快手",
    "Soul": "fmz200 — Soul",
    "Line": "blackmatrix7 — Line",
    "TestFlight": "blackmatrix7 — TestFlight",
}

# TikTok 上游含整域 snssdk.com，会把皮皮虾国内 effect/*-lq.snssdk.com 误判出海。
# 海外解锁仍有 tiktokv.com / isnssdk.com / byteoversea 等，不必绑死 snssdk.com。
DROP_DOMAIN_SUFFIX: dict[str, frozenset[str]] = {
    "TikTok": frozenset({"snssdk.com"}),
}


def apply_drops(name: str, sets: dict[str, set[str]]) -> dict[str, set[str]]:
    drop = DROP_DOMAIN_SUFFIX.get(name)
    if not drop:
        return sets
    suffix = sets.get("domain_suffix_set")
    if suffix:
        sets["domain_suffix_set"] = {d for d in suffix if d.lower() not in drop}
    return sets


def main() -> None:
    if not APP_DIR.is_dir():
        print("skip: no app-lists directory")
        return
    for path in sorted(APP_DIR.glob("*.list")):
        name = path.stem
        sets = parse_surge_list(path.read_text(encoding="utf-8", errors="replace"))
        sets = apply_drops(name, sets)
        if count_sets(sets) == 0:
            print(f"skip empty {name}")
            continue
        header = [
            "# AUTO-GENERATED by scripts/convert-app-rules.py",
            f"# 类型: 分流规则 — {APP_LABELS.get(name, name)}",
            "# Do not edit manually. Updated by GitHub Actions after upstream sync.",
            f"# Source: {path.name}",
        ]
        if name in DROP_DOMAIN_SUFFIX:
            dropped = ", ".join(sorted(DROP_DOMAIN_SUFFIX[name]))
            header.append(f"# Local drop domain_suffix: {dropped}")
        write_egern_sets(OUTPUT_DIR / f"{name}.yaml", sets, header_lines=header)


if __name__ == "__main__":
    main()
