#!/usr/bin/env python3
"""Download NSRingo/iRingo sgmodules as standalone Modules (not merged into collections)."""

from __future__ import annotations

import importlib.util
import json
import ssl
import sys
import urllib.request
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from paths import MODULES

try:
    import yaml
except ImportError:
    yaml = None  # type: ignore

CONFIG = Path(__file__).with_name("iringo-manifest.yaml")
CTX = ssl.create_default_context()
MIRROR = "https://ghproxy.net/"


def load_config() -> dict:
    if not yaml:
        raise SystemExit("PyYAML required")
    return yaml.safe_load(CONFIG.read_text(encoding="utf-8")) or {}


def fetch_bytes(url: str) -> bytes:
    req = urllib.request.Request(url, headers={"User-Agent": "egern-config-sync/1.0"})
    try:
        with urllib.request.urlopen(req, context=CTX, timeout=120) as resp:
            return resp.read()
    except Exception:
        mirror_url = MIRROR + url if not url.startswith(MIRROR) else url
        req = urllib.request.Request(mirror_url, headers={"User-Agent": "egern-config-sync/1.0"})
        with urllib.request.urlopen(req, context=CTX, timeout=120) as resp:
            return resp.read()


def latest_asset_url(repo: str, asset_name: str) -> str:
    api = f"https://api.github.com/repos/{repo}/releases/latest"
    release = json.loads(fetch_bytes(api))
    for asset in release.get("assets", []):
        if asset.get("name") == asset_name:
            return asset["browser_download_url"]
    raise RuntimeError(f"asset {asset_name} not found in latest release of {repo}")


def download_module(repo: str, asset: str, dest: Path) -> None:
    url = latest_asset_url(repo, asset)
    data = fetch_bytes(url)
    head = data[:256].lstrip()
    if head.startswith(b"<!DOCTYPE") or head.startswith(b"<html"):
        raise ValueError(f"invalid payload from {url}")
    dest.write_bytes(data)
    print(f"OK {dest.name} <- {repo} ({len(data)} bytes)")


_merge_spec = importlib.util.spec_from_file_location(
    "merge_adblock_modules", Path(__file__).with_name("merge-adblock-modules.py")
)
_merge = importlib.util.module_from_spec(_merge_spec)
assert _merge_spec.loader is not None
_merge_spec.loader.exec_module(_merge)


def merge_others(items: list[tuple[str, str]], title: str, output: Path) -> None:
    if not items:
        return
    merged = _merge.build_merged_module(
        items[0][1],
        [(name, text) for name, text in items[1:]],
        header_lines=[
            "# AUTO-GENERATED by scripts/download-iringo-modules.py",
            f"# {title}",
            "# Standalone — not included in unlock/adblock collections.",
            "",
        ],
        primary_desc=title,
    )
    output.write_text(merged, encoding="utf-8")
    print(f"OK {output.name} merged ({len(merged.splitlines())} lines)")


def main() -> None:
    data = load_config()
    MODULES.mkdir(parents=True, exist_ok=True)

    for item in data.get("standalone", []):
        dest = MODULES / item["output"]
        try:
            download_module(item["repo"], item["asset"], dest)
        except Exception as exc:
            if dest.exists():
                print(f"KEEP {dest.name}: {exc}")
            else:
                raise

    others = data.get("others_merge") or {}
    loaded: list[tuple[str, str]] = []
    for item in others.get("repos", []):
        url = latest_asset_url(item["repo"], item["asset"])
        text = fetch_bytes(url).decode("utf-8", errors="replace")
        loaded.append((item["repo"].split("/")[-1], text))
    if loaded:
        merge_others(loaded, others.get("title", "iRingo others"), MODULES / others["output"])


if __name__ == "__main__":
    main()
