#!/usr/bin/env python3
"""Merge mirrored author sgmodules into deduplicated collection supplements."""

from __future__ import annotations

import importlib.util
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from paths import MODULES, UPSTREAM_CACHE

_merge_spec = importlib.util.spec_from_file_location(
    "merge_adblock_modules", Path(__file__).with_name("merge-adblock-modules.py")
)
_merge = importlib.util.module_from_spec(_merge_spec)
assert _merge_spec.loader is not None
_merge_spec.loader.exec_module(_merge)
build_merged_module = _merge.build_merged_module
mirror_script_paths = _merge.mirror_script_paths

try:
    import yaml
except ImportError:
    yaml = None  # type: ignore

CONFIG = Path(__file__).with_name("author-repos.yaml")

UNLOCK_KEYWORDS = (
    "解锁",
    "HTTPDNS",
    "httpdns",
    "外链",
    "Spotify",
    "TikTok",
    "Fileball",
    "DNS防泄露",
    "Google搜索重定向",
    "Google重定向",
    "网盘挂载",
    "快捷搜索",
    "拦截HTTPDNS",
    "歌词增强",
    "歌词翻译",
)

FMZ200_SKIP_ADBLOCK = frozenset(
    {
        "blockAds.module",
    }
)

FMZ200_UNLOCK = frozenset(
    {
        "blockHTTPDNS.module",
    }
)


def load_config() -> dict:
    if not yaml:
        raise SystemExit("PyYAML required")
    return yaml.safe_load(CONFIG.read_text(encoding="utf-8")) or {}


def module_kind(filename: str) -> str:
    name = filename.lower()
    if any(k.lower() in name for k in UNLOCK_KEYWORDS):
        return "unlock"
    return "adblock"


def read_modules(directory: Path) -> list[tuple[str, str]]:
    if not directory.is_dir():
        return []
    items: list[tuple[str, str]] = []
    for path in sorted(directory.rglob("*.sgmodule")):
        items.append((path.relative_to(directory).as_posix(), path.read_text(encoding="utf-8", errors="replace")))
    for path in sorted(directory.rglob("*.module")):
        items.append((path.relative_to(directory).as_posix(), path.read_text(encoding="utf-8", errors="replace")))
    return items


def merge_modules(
    title: str,
    desc: str,
    modules: list[tuple[str, str]],
    *,
    primary_name: str | None = None,
) -> str:
    if not modules:
        return ""
    if primary_name:
        primary_text = next(text for name, text in modules if name == primary_name)
        supplements = [(name, text) for name, text in modules if name != primary_name]
    else:
        primary_text = modules[0][1]
        supplements = [(name, text) for name, text in modules[1:]]
    merged = build_merged_module(
        primary_text,
        supplements,
        header_lines=[
            "# AUTO-GENERATED by scripts/generate-author-collection-supplements.py",
            f"# {desc}",
            "# Do not edit manually.",
            "",
        ],
        primary_desc=desc,
    )
    return mirror_script_paths(merged)


def write_if_content(path: Path, content: str) -> None:
    if not content.strip():
        print(f"skip {path.name}: no modules")
        return
    path.write_text(content, encoding="utf-8")
    print(f"wrote {path.name} ({len(content.splitlines())} lines)")


def generate_qingrex() -> None:
    directory = UPSTREAM_CACHE / "qingrex"
    modules = read_modules(directory)
    if not modules:
        print("skip qingrex: no mirrored modules")
        return

    adblock = [(n, t) for n, t in modules if module_kind(n) == "adblock"]
    unlock = [(n, t) for n, t in modules if module_kind(n) == "unlock"]

    adblock_text = merge_modules(
        "可莉去广告合集",
        "可莉/QingRex 全仓库去广告模块合并去重（本地镜像）",
        adblock,
    )
    write_if_content(MODULES / "qingrex-adblock.sgmodule", adblock_text)

    unlock_text = merge_modules(
        "可莉解锁合集",
        "可莉/QingRex 全仓库解锁/增强模块合并去重（本地镜像）",
        unlock,
    )
    write_if_content(MODULES / "qingrex-unlock.sgmodule", unlock_text)


def generate_fmz200() -> None:
    directory = UPSTREAM_CACHE / "fmz200"
    modules = read_modules(directory)
    if not modules:
        print("skip fmz200: no mirrored modules")
        return

    unlock = [(n, t) for n, t in modules if n in FMZ200_UNLOCK or module_kind(n) == "unlock"]
    adblock = [
        (n, t)
        for n, t in modules
        if n not in FMZ200_UNLOCK and n not in FMZ200_SKIP_ADBLOCK and module_kind(n) == "adblock"
    ]

    adblock_text = merge_modules(
        "奶思补充合集",
        "奶思 fmz200 全仓库单 App 模块合并去重（blockAds 主模块之外的补充）",
        adblock,
    )
    write_if_content(MODULES / "fmz200-extra.sgmodule", adblock_text)

    unlock_text = merge_modules(
        "奶思解锁补充",
        "奶思 fmz200 解锁/HTTPDNS 相关模块（本地镜像）",
        unlock,
    )
    write_if_content(MODULES / "fmz200-unlock-extra.sgmodule", unlock_text)


def main() -> None:
    data = load_config()
    for repo in data.get("repos", []):
        if not repo.get("generate_collections") and repo["id"] != "fmz200":
            continue
        if repo["id"] == "qingrex":
            generate_qingrex()
        if repo["id"] == "fmz200":
            generate_fmz200()


if __name__ == "__main__":
    main()
