#!/usr/bin/env python3
"""Merge China direct rule sets into 分流/国内直连.yaml with deduplication."""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from paths import CHINA_DIRECT, ROUTING_UPSTREAM
from routing_list_utils import (
    SET_KEYS,
    count_sets,
    merge_set_dicts,
    parse_egern_sets,
    parse_surge_list,
    write_egern_sets,
)

OUTPUT = CHINA_DIRECT

SOURCES = (
    "Direct",
    "WeChat",
    "Bilibili",
    "AppleCN",
    "ChinaDomain",
    "ChinaIP",
    "ChinaASN",
)

SOURCE_LABELS = {
    "Direct": "Repcz/Tool — 通用直连",
    "WeChat": "Repcz/Tool — 微信",
    "Bilibili": "Repcz/Tool — 哔哩哔哩",
    "AppleCN": "Repcz/Tool — 苹果中国",
    "ChinaDomain": "Repcz/Tool — 国内域名",
    "ChinaIP": "Repcz/Tool — 国内 IP",
    "ChinaASN": "Repcz/Tool — 国内 ASN",
    "Rabbit-China": "Rabbit-Spec — China.list",
    "Rabbit-CIDR": "Rabbit-Spec — ChinaCIDR.list",
    "ResourceSite": "eulac-dev/Proxy — 视频资源站",
    "PanVod": "eulac-dev/Proxy — 网盘点播",
}


def merge_sources() -> tuple[dict[str, set[str]], list[tuple[str, int]], int]:
    parts: list[dict[str, set[str]]] = []
    source_stats: list[tuple[str, int]] = []
    raw_total = 0

    for name in SOURCES:
        path = ROUTING_UPSTREAM / f"{name}.yaml"
        if not path.exists():
            print(f"skip missing {name}.yaml")
            continue
        part = parse_egern_sets(path)
        count = count_sets(part)
        source_stats.append((name, count))
        raw_total += count
        parts.append(part)

    rabbit_china = ROUTING_UPSTREAM / "rabbit" / "China.list"
    if rabbit_china.is_file():
        part = parse_surge_list(rabbit_china.read_text(encoding="utf-8", errors="replace"))
        count = count_sets(part)
        source_stats.append(("Rabbit-China", count))
        raw_total += count
        parts.append(part)

    rabbit_cidr = ROUTING_UPSTREAM / "rabbit" / "ChinaCIDR.list"
    if rabbit_cidr.is_file():
        part = parse_surge_list(rabbit_cidr.read_text(encoding="utf-8", errors="replace"))
        count = count_sets(part)
        source_stats.append(("Rabbit-CIDR", count))
        raw_total += count
        parts.append(part)

    for name in ("ResourceSite", "PanVod"):
        path = ROUTING_UPSTREAM / "eulac" / f"{name}.lsr"
        if not path.is_file():
            print(f"skip missing eulac/{name}.lsr")
            continue
        part = parse_surge_list(path.read_text(encoding="utf-8", errors="replace"))
        count = count_sets(part)
        source_stats.append((name, count))
        raw_total += count
        parts.append(part)

    merged = merge_set_dicts(parts)
    print("merged from:", ", ".join(f"{n}({c})" for n, c in source_stats))
    return merged, source_stats, raw_total


def write_output(
    merged: dict[str, set[str]],
    source_stats: list[tuple[str, int]],
    raw_total: int,
) -> None:
    total = count_sets(merged)
    overlap = raw_total - total
    header = [
        "# AUTO-GENERATED by scripts/merge-china-rules.py",
        "# 类型: 分流规则 — 国内直连（合并去重）",
        "# Do not edit manually. Updated by GitHub Actions after upstream sync.",
        "#",
        "# Merged & deduplicated domestic direct rules:",
    ]
    for name, count in source_stats:
        label = SOURCE_LABELS.get(name, f"upstream — {name}")
        header.append(f"#   {name:<14} — {label} ({count} entries)")
    header.append(f"# Overlap removed: {overlap}")
    write_egern_sets(OUTPUT, merged, header_lines=header)


def main() -> None:
    merged, source_stats, raw_total = merge_sources()
    write_output(merged, source_stats, raw_total)


if __name__ == "__main__":
    main()
