#!/usr/bin/env python3
"""Merge China direct rule sets into Rules/China-Direct.yaml with deduplication."""

from __future__ import annotations

from pathlib import Path

RULES_DIR = Path(__file__).resolve().parent.parent / "Rules"
OUTPUT = RULES_DIR / "China-Direct.yaml"

SET_KEYS = (
    "domain_set",
    "domain_suffix_set",
    "domain_keyword_set",
    "domain_wildcard_set",
    "domain_regex_set",
    "ip_cidr_set",
    "ip_cidr6_set",
    "asn_set",
    "url_regex_set",
    "geoip_set",
    "dest_port_set",
    "user_agent_set",
)

SOURCES = (
    "Direct",
    "WeChat",
    "Bilibili",
    "AppleCN",
    "ChinaDomain",
    "ChinaIP",
    "ChinaASN",
)


def parse_sets(path: Path) -> dict[str, set[str]]:
    sets: dict[str, set[str]] = {k: set() for k in SET_KEYS}
    current: str | None = None
    for line in path.read_text(encoding="utf-8").splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        for key in SET_KEYS:
            if stripped == f"{key}:":
                current = key
                break
        else:
            if current and stripped.startswith("- "):
                value = stripped[2:].strip().strip('"').strip("'")
                if value:
                    sets[current].add(value)
            elif stripped.endswith(":") and not stripped.startswith("-"):
                current = None
    return sets


SOURCE_LABELS = {
    "Direct": "Repcz/Tool — 通用直连",
    "WeChat": "Repcz/Tool — 微信",
    "Bilibili": "Repcz/Tool — 哔哩哔哩",
    "AppleCN": "Repcz/Tool — 苹果中国",
    "ChinaDomain": "Repcz/Tool — 国内域名",
    "ChinaIP": "Repcz/Tool — 国内 IP",
    "ChinaASN": "Repcz/Tool — 国内 ASN",
}


def merge_sources() -> tuple[dict[str, set[str]], list[tuple[str, int]], int]:
    merged: dict[str, set[str]] = {k: set() for k in SET_KEYS}
    source_stats: list[tuple[str, int]] = []
    raw_total = 0
    for name in SOURCES:
        path = RULES_DIR / f"{name}.yaml"
        if not path.exists():
            print(f"skip missing {name}.yaml")
            continue
        part = parse_sets(path)
        count = sum(len(part[k]) for k in SET_KEYS)
        source_stats.append((name, count))
        raw_total += count
        for key in SET_KEYS:
            merged[key].update(part[key])
    print("merged from:", ", ".join(f"{n}({c})" for n, c in source_stats))
    return merged, source_stats, raw_total


def write_output(
    merged: dict[str, set[str]],
    source_stats: list[tuple[str, int]],
    raw_total: int,
) -> None:
    total = sum(len(merged[k]) for k in SET_KEYS)
    overlap = raw_total - total
    lines = [
        "# AUTO-GENERATED by scripts/merge-china-rules.py",
        "# Do not edit manually. Updated by GitHub Actions after upstream sync.",
        "#",
        "# Merged & deduplicated domestic direct rules:",
    ]
    for name, count in source_stats:
        label = SOURCE_LABELS.get(name, f"Repcz/Tool — {name}")
        lines.append(f"#   {name:<12} — {label} ({count} entries)")
    lines.append(f"# Overlap removed: {overlap}")
    lines.append(f"# Total unique entries: {total}")
    lines.append("")
    lines.append("no_resolve: true")
    for key in SET_KEYS:
        values = sorted(merged[key])
        if not values:
            continue
        lines.append(f"{key}:")
        for value in values:
            if any(c in value for c in ':"[]{}#&*!|>\\'):
                lines.append(f'  - "{value}"')
            else:
                lines.append(f"  - {value}")
    lines.append("")
    OUTPUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUTPUT.name}: {total} entries (overlap removed {overlap})")


def main() -> None:
    merged, source_stats, raw_total = merge_sources()
    write_output(merged, source_stats, raw_total)


if __name__ == "__main__":
    main()
