#!/usr/bin/env python3
"""Merge AI routing rules from Repcz, VPSDance, Sukka, and local supplement."""

from __future__ import annotations

import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from paths import ROUTING_FOREIGN, ROUTING_UPSTREAM

OUTPUT = ROUTING_FOREIGN / "AI-Merged.yaml"
REPCZ_AI = ROUTING_FOREIGN / "AI.yaml"
VPSDANCE_AI = ROUTING_UPSTREAM / "ai" / "vpsdance-all.yaml"
SKK_AI = ROUTING_UPSTREAM / "skk" / "ai.conf"
LOCAL_SUPPLEMENT = ROUTING_FOREIGN / "AI-supplement.yaml"

SET_KEYS = (
    "domain_set",
    "domain_suffix_set",
    "domain_keyword_set",
    "domain_wildcard_set",
    "domain_regex_set",
    "url_regex_set",
)

SOURCE_LABELS = {
    "Repcz-AI": "Repcz/Tool — AI.yaml",
    "VPSDance": "VPSDance/ai-proxy-rules — egern/all.yaml",
    "Sukka-ai": "Sukka ruleset.skk.moe — non_ip/ai.conf",
    "local": "oo226/egern-config — AI-supplement.yaml",
}


def parse_egern_sets(path: Path) -> dict[str, set[str]]:
    sets: dict[str, set[str]] = {k: set() for k in SET_KEYS}
    if not path.is_file():
        return sets
    current: str | None = None
    for line in path.read_text(encoding="utf-8").splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        for key in SET_KEYS:
            if stripped == f"{key}:":
                current = key
                break
        else:
            if current and stripped.startswith("- "):
                value = stripped[2:].strip().strip('"').strip("'")
                if value:
                    sets[current].add(value)
            elif stripped.endswith(":") and not stripped.startswith("-"):
                current = None
    return sets


def parse_skk_ai(path: Path) -> dict[str, set[str]]:
    sets: dict[str, set[str]] = {k: set() for k in SET_KEYS}
    if not path.is_file():
        return sets
    for line in path.read_text(encoding="utf-8").splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        if stripped.startswith("DOMAIN,"):
            value = stripped.split(",", 1)[1].strip()
            if value and "5ukk4w" not in value:
                sets["domain_set"].add(value)
        elif stripped.startswith("DOMAIN-SUFFIX,"):
            value = stripped.split(",", 1)[1].strip()
            if value:
                sets["domain_suffix_set"].add(value)
        elif stripped.startswith("DOMAIN-KEYWORD,"):
            value = stripped.split(",", 1)[1].strip()
            if value:
                sets["domain_keyword_set"].add(value)
    return sets


def merge_sources() -> tuple[dict[str, set[str]], list[tuple[str, int]], int]:
    sources = [
        ("Repcz-AI", parse_egern_sets(REPCZ_AI)),
        ("VPSDance", parse_egern_sets(VPSDANCE_AI)),
        ("Sukka-ai", parse_skk_ai(SKK_AI)),
        ("local", parse_egern_sets(LOCAL_SUPPLEMENT)),
    ]
    merged: dict[str, set[str]] = {k: set() for k in SET_KEYS}
    source_stats: list[tuple[str, int]] = []
    raw_total = 0
    for name, part in sources:
        count = sum(len(part[k]) for k in SET_KEYS)
        if count == 0:
            print(f"skip empty source {name}")
            continue
        source_stats.append((name, count))
        raw_total += count
        for key in SET_KEYS:
            merged[key].update(part[key])
    return merged, source_stats, raw_total


def write_output(
    merged: dict[str, set[str]],
    source_stats: list[tuple[str, int]],
    raw_total: int,
) -> None:
    total = sum(len(merged[k]) for k in SET_KEYS)
    overlap = raw_total - total
    lines = [
        "# AUTO-GENERATED by scripts/merge-ai-rules.py",
        "# 类型: 分流规则 — AI 服务（多源合并去重）",
        "# Do not edit manually. Updated by GitHub Actions after upstream sync.",
        "#",
        "# Sources:",
    ]
    for name, count in source_stats:
        label = SOURCE_LABELS.get(name, name)
        lines.append(f"#   {name:<12} — {label} ({count} entries)")
    lines.append(f"# Overlap removed: {overlap}")
    lines.append(f"# Total unique entries: {total}")
    lines.append("")
    lines.append("no_resolve: true")
    for key in SET_KEYS:
        values = sorted(merged[key], key=str.lower)
        if not values:
            continue
        lines.append(f"{key}:")
        for value in values:
            if any(c in value for c in ':"[]{}#&*!|>\\'):
                lines.append(f'  - "{value}"')
            else:
                lines.append(f"  - {value}")
    lines.append("")
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUTPUT.name}: {total} entries (overlap removed {overlap})")


def main() -> None:
    merged, source_stats, raw_total = merge_sources()
    if not source_stats:
        raise SystemExit("no AI rule sources found")
    write_output(merged, source_stats, raw_total)


if __name__ == "__main__":
    main()
