#!/usr/bin/env python3
"""Merge China direct rule sets into Rules/China-Direct.yaml with deduplication."""

from __future__ import annotations

from pathlib import Path

RULES_DIR = Path(__file__).resolve().parent.parent / "Rules"
OUTPUT = RULES_DIR / "China-Direct.yaml"

SET_KEYS = (
    "domain_set",
    "domain_suffix_set",
    "domain_keyword_set",
    "domain_wildcard_set",
    "domain_regex_set",
    "ip_cidr_set",
    "ip_cidr6_set",
    "asn_set",
    "url_regex_set",
    "geoip_set",
    "dest_port_set",
    "user_agent_set",
)

SOURCES = (
    "Direct",
    "WeChat",
    "Bilibili",
    "AppleCN",
    "ChinaDomain",
    "ChinaIP",
    "ChinaASN",
)


def parse_sets(path: Path) -> dict[str, set[str]]:
    sets: dict[str, set[str]] = {k: set() for k in SET_KEYS}
    current: str | None = None
    for line in path.read_text(encoding="utf-8").splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        for key in SET_KEYS:
            if stripped == f"{key}:":
                current = key
                break
        else:
            if current and stripped.startswith("- "):
                value = stripped[2:].strip().strip('"').strip("'")
                if value:
                    sets[current].add(value)
            elif stripped.endswith(":") and not stripped.startswith("-"):
                current = None
    return sets


def merge_sources() -> dict[str, set[str]]:
    merged: dict[str, set[str]] = {k: set() for k in SET_KEYS}
    stats: list[str] = []
    for name in SOURCES:
        path = RULES_DIR / f"{name}.yaml"
        if not path.exists():
            print(f"skip missing {name}.yaml")
            continue
        part = parse_sets(path)
        count = sum(len(part[k]) for k in SET_KEYS)
        stats.append(f"{name}({count})")
        for key in SET_KEYS:
            merged[key].update(part[key])
    print("merged from:", ", ".join(stats))
    return merged


def write_output(merged: dict[str, set[str]]) -> None:
    lines = [
        "# AUTO-GENERATED by scripts/merge-china-rules.py",
        "# Sources: Direct, WeChat, Bilibili, AppleCN, ChinaDomain, ChinaIP, ChinaASN",
        "# Do not edit manually. Updated by GitHub Actions after upstream sync.",
        "",
        "no_resolve: true",
    ]
    total = 0
    for key in SET_KEYS:
        values = sorted(merged[key])
        if not values:
            continue
        lines.append(f"{key}:")
        for value in values:
            if any(c in value for c in ':"[]{}#&*!|>\\'):
                lines.append(f'  - "{value}"')
            else:
                lines.append(f"  - {value}")
        total += len(values)
    lines.append("")
    OUTPUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUTPUT.name}: {total} entries")


def main() -> None:
    merged = merge_sources()
    write_output(merged)


if __name__ == "__main__":
    main()
