#!/usr/bin/env python3
"""Merge Repcz Reject.yaml and Sukka reject.conf into Rules/Reject-Merged.yaml."""

from __future__ import annotations

from pathlib import Path

RULES_DIR = Path(__file__).resolve().parent.parent / "Rules"
REPCZ = RULES_DIR / "Reject.yaml"
SKK = RULES_DIR / "skk" / "reject.conf"
OUTPUT = RULES_DIR / "Reject-Merged.yaml"

SET_KEYS = (
    "domain_set",
    "domain_suffix_set",
    "domain_keyword_set",
    "domain_wildcard_set",
    "domain_regex_set",
    "ip_cidr_set",
    "ip_cidr6_set",
    "user_agent_set",
)


def parse_repcz(path: Path) -> dict[str, set[str]]:
    sets: dict[str, set[str]] = {k: set() for k in SET_KEYS}
    current: str | None = None
    for line in path.read_text(encoding="utf-8").splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        for key in SET_KEYS:
            if stripped == f"{key}:":
                current = key
                break
        else:
            if current and stripped.startswith("- "):
                value = stripped[2:].strip().strip('"').strip("'")
                if value:
                    sets[current].add(value)
            elif stripped.endswith(":") and not stripped.startswith("-"):
                current = None
    return sets


def parse_skk(path: Path) -> tuple[set[str], set[str]]:
    domains: set[str] = set()
    suffixes: set[str] = set()
    for line in path.read_text(encoding="utf-8").splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        if stripped.startswith("."):
            suffixes.add(stripped[1:])
        else:
            domains.add(stripped)
    return domains, suffixes


def count_entries(sets: dict[str, set[str]]) -> int:
    return sum(len(sets[k]) for k in SET_KEYS)


def merge() -> dict[str, set[str]]:
    repcz = parse_repcz(REPCZ)
    skk_domains, skk_suffixes = parse_skk(SKK)

    merged: dict[str, set[str]] = {k: set(repcz[k]) for k in SET_KEYS}
    merged["domain_set"].update(skk_domains)
    merged["domain_suffix_set"].update(skk_suffixes)

    repcz_total = count_entries(repcz)
    skk_total = len(skk_domains) + len(skk_suffixes)
    merged_total = count_entries(merged)
    overlap = repcz_total + skk_total - merged_total

    print(
        f"reject merge: repcz={repcz_total}, skk={skk_total}, "
        f"merged={merged_total}, overlap_removed={overlap}"
    )
    return merged, repcz, skk_domains, skk_suffixes, overlap


def write_output(
    merged: dict[str, set[str]],
    repcz: dict[str, set[str]],
    skk_domains: set[str],
    skk_suffixes: set[str],
    overlap: int,
) -> None:
    repcz_total = count_entries(repcz)
    skk_total = len(skk_domains) + len(skk_suffixes)
    merged_total = count_entries(merged)

    lines = [
        "# AUTO-GENERATED by scripts/merge-reject-rules.py",
        "# Do not edit manually. Updated by GitHub Actions after upstream sync.",
        "#",
        "# Merged & deduplicated ad-blocking domain rules:",
        f"#   Repcz/Reject.yaml — {repcz_total} entries "
        "(domain / suffix / keyword / ip / user-agent)",
        f"#   Sukka/reject.conf  — {skk_total} entries "
        f"({len(skk_domains)} domains + {len(skk_suffixes)} suffixes)",
        f"# Overlap removed: {overlap}",
        f"# Total unique entries: {merged_total}",
        "",
        "no_resolve: true",
    ]

    for key in SET_KEYS:
        values = sorted(merged[key])
        if not values:
            continue
        lines.append(f"{key}:")
        for value in values:
            if any(c in value for c in ':"[]{}#&*!|>\\'):
                lines.append(f'  - "{value}"')
            else:
                lines.append(f"  - {value}")
    lines.append("")

    OUTPUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUTPUT.name}: {merged_total} entries")


def main() -> None:
    if not REPCZ.exists():
        raise SystemExit(f"missing {REPCZ}")
    if not SKK.exists():
        raise SystemExit(f"missing {SKK}")
    merged, repcz, skk_domains, skk_suffixes, overlap = merge()
    write_output(merged, repcz, skk_domains, skk_suffixes, overlap)


if __name__ == "__main__":
    main()
